/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thesurveymanager.screens;

import thesurveymanager.TheSurveyManager;

/**
 *
 * @author IESA CNEC
 */
public class ResultsScreen extends javax.swing.JFrame {

    /**
     * Creates new form ResultsScreen
     */
    public ResultsScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jTextArea1.setRows(5);
        TheSurveyManager.questions.forEach(question -> {
            int percentage;

            jTextArea1.append("\n " + question.getMessage());

            //---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
            if(question.getAlternatives().get(0).getCount() == 0) {
                percentage = 0;
            }
            else {
                percentage = question.getAnswerCount() * 100 / question.getAlternatives().get(0).getCount();
            }
            jTextArea1.append("\n    a) " + question.getAlternatives().get(0).getMessage() + " --- " + question.getAlternatives().get(0).getCount() + " --- " + percentage + "%");
            //---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
            if(question.getAlternatives().get(1).getCount() == 0) {
                percentage = 0;
            }
            else {
                percentage = question.getAnswerCount() * 100 / question.getAlternatives().get(1).getCount();
            }
            jTextArea1.append("\n    b) " + question.getAlternatives().get(1).getMessage() + " --- " + question.getAlternatives().get(1).getCount() + " --- " + percentage + "%");
            //---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
            if(question.getAlternatives().get(2).getCount() == 0) {
                percentage = 0;
            }
            else {
                percentage = question.getAnswerCount() * 100 / question.getAlternatives().get(2).getCount();
            }
            jTextArea1.append("\n    c) " + question.getAlternatives().get(2).getMessage() + " --- " + question.getAlternatives().get(2).getCount() + " --- " + percentage + "%");
            //---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
            if(question.getAlternatives().get(3).getCount() == 0) {
                percentage = 0;
            }
            else {
                percentage = question.getAnswerCount() * 100 / question.getAlternatives().get(3).getCount();
            }
            jTextArea1.append("\n    d) " + question.getAlternatives().get(3).getMessage() + " --- " + question.getAlternatives().get(3).getCount() + " --- " + percentage + "%");
            //---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
            if(question.getAlternatives().get(4).getCount() == 0) {
                percentage = 0;
            }
            else {
                percentage = question.getAnswerCount() * 100 / question.getAlternatives().get(4).getCount();
            }
            jTextArea1.append("\n    e) " + question.getAlternatives().get(4).getMessage() + " --- " + question.getAlternatives().get(4).getCount() + " --- " + percentage + "%");
            //---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

            jTextArea1.append("\n \n");
        });

        jTextArea1.setEditable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        TheSurveyManager.user_interface.init();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultsScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
